name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸Ivy Gym
        uses: actions/checkout@v2
        with:
          path: gym
          persist-credentials: false

      - name: Checkout ðŸ›Žï¸Ivy
        uses: actions/checkout@v2
        with:
          path: gym/ivy
          submodules: "recursive"
          persist-credentials: false

      - name: Install Dependencies
        continue-on-error: true
        run: |
          pip install --user -e gym/ivy
          pip install -r gym/ivy/requirements/requirements.txt
          pip install -r gym/ivy/requirements/optional.txt
          pip install -r gym/requirements.txt
          pip install pytest
      
      - name: Run Tests
        env: 
          USER_API_KEY: ${{secrets.USER_API_KEY}}
        run: |
          cd gym
          mkdir .ivy
          touch .ivy/key.pem
          echo $USER_API_KEY >> .ivy/key.pem
          python -m pytest ivy_gym_tests/
