name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸Ivy Gym
        uses: actions/checkout@v2
        with:
          path: gym
          persist-credentials: false

      - name: Checkout ðŸ›Žï¸Ivy
        uses: actions/checkout@v2
        with:
          path: gym/ivy
          submodules: "recursive"
          persist-credentials: false
      
      - name: Run Tests
        run: |
          cd gym
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          docker run --rm -v `pwd`:/gym -v `pwd`/ivy:/ivy/ivy unifyai/gym:latest python3 -m pytest ivy_gym_tests/
