name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy Gym
        uses: actions/checkout@v2
        with:
          path: gym
          persist-credentials: false

      - name: Run Tests
        run: |
          cd gym
          docker run --rm -v `pwd`:/gym unifyai/gym:latest python3 -m pytest gym/ivy_gym_tests/
