name: tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy Gym
        uses: actions/checkout@v2
        with:
          path: ivy_gym
          persist-credentials: false

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/ivy_gym:/ivy_gym ivydl/ivy-gym:latest python3 -m pytest ivy_gym_tests/
